### PR TITLE
Alerting: Add Option to get all alert rules

### PR DESCRIPTION
**Pull request by flkhndlr**
Adding the feature to get all alert rules.
Uses the standard API.( see here https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/#span-idroute-get-alert-rulesspan-get-all-the-alert-rules-_routegetalertrules)

### CODE REVIEW

**Comment by PhilipPenquitt** [comment]
Hi, @julienduchesne I signed the cla, so the review could start, I guess?

Greetings

**Comment by m-rcl** [comment]
@PhilipPenquitt I think the PR needs to be rebased first. I would highly appreciate to have this merged soon :smiley:

**Comment by flkhndlr** [comment]
I think the PR should now be ready. @julienduchesne or @alexweav would you  be so kind to review this PR. I'd really appreciate that. Thanks in advance!

**Comment by PhilipPenquitt** [comment]
Hey @m-rcl,
could you take a look into the review? Thanks in advance!

**Comment by flkhndlr** [comment]
hey @gouthamve ,

a few weeks ago I spoke to you about this PR at the Meetup in Berlin. Would you be so nice and look into this PR?

Thanks in advance

**Comment by JanSF** [comment]
It would be awesome to revive this PR, as Unified Alerts have these new API endpoints.

**Comment by maikelvl** [comment]
Can this PR be merged @julienduchesne ? I would like to use it as well 😊

**Comment by rndmh3ro** [comment]
Is there anyone at grafana who can take a look here?

**Comment by julienduchesne** [comment]
This client is being deprecated soon. This is implemented in the client generated from openapi: https://github.com/grafana/grafana-openapi-client-go/blob/main/client/provisioning/provisioning_client.go#L58. 

I can merge this PR with a caveat: I'm not going to test it

**Review by julienduchesne — APPROVED** [review]

**Pull request merged**
