### PR TITLE
add an update datasource by uid function

### PR DESCRIPTION
**Pull request by rdubrock**

### CODE REVIEW

**Review by inkel — APPROVED** [review]
Approving because I understand you need this, but perhaps we should only have one `UpdateDataSource` function that uses the UID if the ID wasn't provided. @julienduchesne thoughts?

**Comment by rdubrock** [comment]
> but perhaps we should only have one UpdateDataSource

I'd be happy to make that change! I'm not sure what that would do to backwards compatibility because I'm not sure what all this library gets used for.

**Comment by inkel** [comment]
Well, afaik this library is only used by the Terraform Provider for Grafana, so we have fairly enough control not to wreak too much havoc by doing that.

**Review by julienduchesne — APPROVED** [review]
We still use this lib for Grafana 7 in the provider, updating by UID was not supported back then: https://grafana.com/docs/grafana/v7.5/http_api/data_source/#update-an-existing-data-source. I think 2 functions is best at keeping retrocompat. LGTM!

**Comment by rdubrock** [comment]
🎉 Thanks y'all!

**Comment by julienduchesne** [comment]
We _could_ break compatibility with Grafana 7 but I personally like keeping support for as long as possible

**Pull request merged**
